config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'packs/:role', to: 'pages#packs', role: /visitante|comerciante/, as: :packs
  get 'blog', to: 'pages#blog', as: :blog
  get 'article/:id', to: 'pages#article', as: :article
  get 'terms-and-conditions', to: 'pages#terms_and_conditions', as: :terms_and_conditions
  get 'privacy-policy', to: 'pages#privacy_policy', as: :privacy_policy
  get 'reset-password', to: 'pages#reset_password', as: :reset_password
  resources :contacts, only: :create
  

end

app/models/contact.rb
class Contact < ActiveResource::Base
  self.site = ENV['api_url']
  add_response_method :http_response

  # def self.unread
  #   Contact.all(params: { f: { scopes: { read: 0 } }.to_json })
  # end

  schema do
    string :name
    string :email
    string :tel
    text :message
    integer :role
    integer :subject
    boolean :read
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    resource_params = {}
    resource_params[:f] = params[:f].to_json if params[:f].present?
    resource_params[:page] = params[:page].present? ? params[:page] : 1

    @contacts = Contact.all(params: resource_params)

    @contacts = Kaminari::PaginatableArray.new(@contacts,{
      limit: @contacts.http_response['X-limit'].to_i,
      offset: @contacts.http_response['X-offset'].to_i,
      total_count: @contacts.http_response['X-total'].to_i
    })
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact.update_attribute(:read, true)
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.js { render :show, status: :created, location: @contact }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.js { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update_attributes(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # PATCH/PUT /contacts.js
  def update_many
    begin
      Contact.put(:many, contact_params.merge({ ids: params[:ids] }))
    rescue
      @contacts_errors = ['Unable to update selected contacts']
    end
    @contacts = Contact.all(params: { f: { find: params[:ids] }.to_json })
    render :index
  end

  # DELETE /contacts.js
  def destroy_many
    param_ids = { ids: params[:ids] }
    begin
      Contact.delete(:many, param_ids)
      render js: 'window.location.reload()'
    rescue
      @contacts = Contact.all(params: { f: { find: params[:ids] }.to_json })
      @contacts_errors = ['Unable to delete selected contacts']
      render :index
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :tel, :message, :role, :subject, :read)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_contact.html.erb
<% selected = false unless local_assigns.has_key? :selected %>

<tr class="<%= 'active' unless contact.read %>" data-member-id="<%= contact.id %>">
	<td>
		<label class="checkbox-inline">
			<input class="collection-methods" type="checkbox" name="contact[ids][]" id="contact_id_<%= contact.id %>" value="<%= contact.id %>" <%= 'checked' if selected %>>
		</label>
	</td>
	<td><%= contact.name %></td>
	<td><%= contact.email %></td>
	<td><%= contact.tel %></td>
	<td><%= { client: 'Visitante', seller: 'Comerciante' }[contact.role.try(:to_sym)] %></td>
	<td><%= { contact: 'Contacto' }[contact.subject.try(:to_sym)] %></td>
	<td>
		<div class="btn-group btn-group-xs" role="group" aria-label="...">
			<%= link_to '<i class="fa fa-eye" aria-hidden="true"></i>'.html_safe, contact, class: 'btn btn-default' %>
			<%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_contact_path(contact), class: 'btn btn-info' %>
			<%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
		</div>
	</td>
</tr>

app/views/contacts/_form.html.erb
<% content_for :extra_js do %>
  $('.new_contact, .edit_contact').validate({
    rules: {
      'contact[tel]': {
        pattern: /^(?:[0-9\+\-\(\)\s]+)$/,
        minlength: 6,
        maxlength: 20
      }
    },
    messages: {
      'contact[tel]': {
        pattern: 'Ingresá un teléfono válido'
      }
    }
  });
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <%= action_name == 'edit' ? 'Editar' : 'Agregar' %> Contacto
    <%= link_to contacts_path, class: 'btn btn-xs btn-warning pull-right' do %>
      <i class="fa fa-arrow-left" aria-hidden="true"></i> Volver
    <% end %>
  </div>
  <div class="panel-body">
    <%= form_for(@contact) do |f| %>
      <% if @contact.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

          <ul>
          <% @contact.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <%= f.label :name, 'Nombre', class: 'control-label col-sm-3' %>
        <div class="col-sm-9">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Nombre y apellido', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :email, 'Email', class: 'control-label col-sm-3' %>
        <div class="col-sm-9">
          <%= f.email_field :email, class: 'form-control', placeholder: 'Email', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :tel, 'Teléfono', class: 'control-label col-sm-3' %>
        <div class="col-sm-9">
          <%= f.text_field :tel, class: 'form-control', placeholder: 'Teléfono' %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :role, 'Típo de usuario', class: 'control-label col-sm-3' %>
        <div class="col-sm-9">
          <%= f.select :role, [ ['Visitante', :client], ['Comerciante', :seller] ], { include_blank: 'Seleccioná' }, class: 'form-control', required: true %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :message, 'Mensaje', class: 'control-label col-sm-3' %>
        <div class="col-sm-9">
          <%= f.text_area :message, class: 'form-control', placeholder: 'Mensaje', rows: 4, required: true, minlength: 15 %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-sm-9 col-sm-offset-3">
          <%= f.submit class: 'btn btn-default' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/edit.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Contacto de <%= @contact.name %> <small><%= @contact.email %></small></h1>
		<%= render 'form' %>
	</div>
</div>

app/views/contacts/index.html.erb
<% content_for :extra_js do %>
  Utils.filtersForm();
  Utils.checkboxes();
<% end %>

<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Contactos
      <%= link_to 'Agregar contacto', new_contact_path, class: 'btn btn-primary pull-right' %>
    </h1>
    <div class="filters-table">
      <form id="filters_form" method="get">
        <input type="hidden" name="f[order]" id="f_order" value="<%= params[:f][:order].to_s rescue nil %>">
        <div class="form-group">
          <div class="col-xs-12 mb-10">
            <input type="search" class="form-control" id="f_search" name="f[search]" placeholder="Busqueda por palabra" value="<%= params[:f][:search] rescue nil %>">
          </div>
          <div class="col-xs-3 mb-10">
            <select id="f_scopes_role" class="form-control" name="f[scopes][role]">
              <option value="">Tipo de usuario</option>
              <option value="client" <%= 'selected="selected"' if params[:f][:scopes][:role].to_sym == :client rescue nil %>>Visitante</option>
              <option value="seller" <%= 'selected="selected"' if params[:f][:scopes][:role].to_sym == :seller rescue nil %>>Comerciante</option>
            </select>
          </div>
          <div class="col-xs-3 mb-10">
            <select id="f_scopes_read" class="form-control" name="f[scopes][read]">
              <option value="">Todos los mensajes</option>
              <option value="0" <%= 'selected="selected"' if params[:f][:scopes][:read] == 0.to_s rescue nil %>>No Leídos</option>
              <option value="1" <%= 'selected="selected"' if params[:f][:scopes][:read] == 1.to_s rescue nil %>>Leídos</option>
            </select>
          </div>
          <div class="col-xs-3">
            <a href="<%= contacts_path %>" class="btn btn-default btn-block">Limpiar filtros</a>
          </div>
          <div class="col-xs-3">
            <button type="submit" class="btn btn-primary btn-block">Buscar</button>
          </div>
        </div>
      </form>
    </div>
    <% if @contacts.blank? %>
      <h5 class="blank-search">No se encontraron contactos que coincidan con tu búsqueda</h5>
    <% else %>
      <table class="table table-controls" width="100%">
        <thead>
          <tr>
            <th>
              <label class="checkbox-inline">
                <input type="checkbox" name="select_all" data-target=".collection-methods">
              </label>
            </th>
            <th>
              <a href="#" data-order="name">
                Nombre
                <small>
                  <i class="fa fa-sort<%= (params[:f][:order].starts_with?('name_') ? '-' + params[:f][:order][/(?:asc|desc)$/] : nil) rescue nil %>" aria-hidden="true"></i>
                </small>
              </a>
            </th>
            <th>
              <a href="#" data-order="email">
                Email
                <small>
                  <i class="fa fa-sort<%= (params[:f][:order].starts_with?('email_') ? '-' + params[:f][:order][/(?:asc|desc)$/] : nil) rescue nil %>" aria-hidden="true"></i>
                </small>
              </a>
            </th>
            <th>
              <a href="#" data-order="tel">
                Teléfono
                <small>
                  <i class="fa fa-sort<%= (params[:f][:order].starts_with?('tel_') ? '-' + params[:f][:order][/(?:asc|desc)$/] : nil) rescue nil %>" aria-hidden="true"></i>
                </small>
              </a>
            </th>
            <th>
              <a href="#" data-order="role">
                Tipo Usuario
                <small>
                  <i class="fa fa-sort<%= (params[:f][:order].starts_with?('role_') ? '-' + params[:f][:order][/(?:asc|desc)$/] : nil) rescue nil %>" aria-hidden="true"></i>
                </small>
              </a>
            </th>
            <th>
              <a href="#" data-order="subject">
                Asunto
                <small>
                  <i class="fa fa-sort<%= (params[:f][:order].starts_with?('subject_') ? '-' + params[:f][:order][/(?:asc|desc)$/] : nil) rescue nil %>" aria-hidden="true"></i>
                </small>
              </a>
            </th>
            <th class="text-right">
              <div class="btn-group btn-group-xs" role="group" aria-label="...">
                <%= form_for contacts_path, method: :put, format: :js, remote: true, html: { class: 'collection-methods' } do |f| %>
                  <%= hidden_field_tag 'contact[read]', 1 %>
                  <%= f.button type: :submit, class: 'btn btn-default', disabled: true do %>
                    <i class="fa fa-eye" aria-hidden="true"></i>
                  <% end %>
                <% end %>
                <%= form_for contacts_path, method: :put, format: :js, remote: true, html: { class: 'collection-methods' } do |f| %>
                  <%= hidden_field_tag 'contact[read]', 0 %>
                  <%= f.button type: :submit, class: 'btn btn-warning', disabled: true do %>
                    <i class="fa fa-eye-slash" aria-hidden="true"></i>
                  <% end %>
                <% end %>
                <%= form_for contacts_path, method: :delete, format: :js, remote: true, data: { confirm: 'Are you sure?' }, html: { class: 'collection-methods' } do |f| %>
                  <%= f.button type: :submit, class: 'btn btn-danger', disabled: true do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </div>
            </th>
          </tr>
        </thead>

        <tbody>
          <%= render @contacts %>
        </tbody>
      </table>
    <% end %>
    <div class="pagination-table">
      <%= paginate @contacts %>
    </div>
  </div>
</div>

app/views/contacts/index.js.erb
var contact_error = '<%= @contacts_errors[0] rescue nil %>';
var $contacts = $('<%= j render @contacts, selected: true %>');
var $tr = $('tbody tr');
$contacts.each(function() {
	var $contact = $(this);
	var id = $contact.data('member-id');
	$tr.filter('[data-member-id=' + id + ']').replaceWith($contact);
});
if (!!contact_error) Utils.notification('alert', contact_error);
Utils.checkboxes();
Utils.loader().hide();

app/views/contacts/new.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Nuevo contacto</h1>
		<%= render 'form' %>
	</div>
</div>

app/views/contacts/new.js.erb
var errors = JSON.parse("<%= j @contact.errors.to_json.html_safe %>");
var response = 'Ocurrió un error al envíar tu contacto:<br>' + (function() {
	for (var key in errors) return errors[key][0];
})();
Utils.insertFormResponse(document.getElementById('new_contact'), response, 2000);
Utils.notification('notice', 'Revisá los datos.');
Utils.loader().hide();
console.info('Contact Error', errors);

app/views/contacts/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">
      Datos de Contacto
      <%= link_to 'Agregar contacto', new_contact_path, class: 'btn btn-primary pull-right' %>
    </h1>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_contact_path(@contact), class: 'btn btn-xs btn-info' %>
        <%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, @contact, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-xs btn-danger' %>
        <strong>Contacto de <%= @contact.name %> <small><%= @contact.email %></small></strong>
        <%= link_to contacts_path, class: 'btn btn-xs btn-warning pull-right' do %>
          <i class="fa fa-arrow-left" aria-hidden="true"></i> Volver
        <% end %>
      </div>
      <div class="panel-body">
        <p><strong>Nombre:</strong> <%= @contact.name %></p>
        <p><strong>Email:</strong> <%= @contact.email %></p>
        <p><strong>Tipo de usuario:</strong> <%= { client: 'Visitante', seller: 'Comerciante' }[@contact.role.try(:to_sym)] %></p>
        <p><strong>Teléfono:</strong> <%= @contact.tel %></p>
        <p><strong>Asunto:</strong> <%= { contact: 'Contacto' }[@contact.subject.try(:to_sym)] %></p>
        <p><strong>Mensaje:</strong> <%= @contact.message.html_safe %></p>
      </div>
    </div>
  </div>
</div>

app/views/contacts/show.js.erb
var contact = JSON.parse("<%= j @contact.to_json.html_safe %>");
var response = 'Gracias por contactarte ' + contact.name + ', reponderemos tu consulta a la brevedad.';
var form = document.getElementById('new_contact');
$(form).submit(function(){return false});
Utils.insertFormResponse(form, response);
Utils.notification('notice', 'Contacto enviado con exito.');
Utils.loader().hide();