config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  get 'packs/:role', to: 'pages#packs', role: /visitante|comerciante/, as: :packs
  get 'blog', to: 'pages#blog', as: :blog
  get 'article/:id', to: 'pages#article', as: :article
  get 'terms-and-conditions', to: 'pages#terms_and_conditions', as: :terms_and_conditions
  get 'privacy-policy', to: 'pages#privacy_policy', as: :privacy_policy
  get 'reset-password', to: 'pages#reset_password', as: :reset_password
  resources :contacts, only: :create
  

end

app/models/category.rb
class Category < ActiveResource::Base
  self.site = ENV['api_url']
  add_response_method :http_response

  schema do
  	string :title
  	string :ancestry
  end
end

app/models/contact.rb
class Contact < ActiveResource::Base
  self.site = ENV['api_url']
  add_response_method :http_response

  # def self.unread
  #   Contact.all(params: { f: { scopes: { read: 0 } }.to_json })
  # end

  schema do
    string :name
    string :email
    string :tel
    text :message
    integer :role
    integer :subject
    boolean :read
  end
end

app/models/image.rb
class Image < ActiveResource::Base
  self.site = ENV['api_url']
end

app/models/payment.rb
class Payment < ActiveResource::Base
  self.site = ENV['api_url']
end

app/models/product.rb
class Product < ActiveResource::Base
  self.site = ENV['api_url']
end

app/models/promotion.rb
class Promotion < ActiveResource::Base
  self.site = ENV['api_url']
end

app/models/shed.rb
class Shed < ActiveResource::Base
  self.site = ENV['api_url']
end

app/models/shop.rb
class Shop < ActiveResource::Base
  self.site = ENV['api_url']
  add_response_method :http_response

  cattr_accessor :static_headers
  self.static_headers = headers

  def self.headers
    new_headers = static_headers.clone
    new_headers = new_headers.merge(JSON.parse(self.user)) if self.user.present?
    new_headers
  end

  schema do
  	integer :user_id
  	integer :shed_id
  	integer :category_id
  	string :description
  	integer :location
  	string :location_detail
  	integer :location_floor
  	integer :location_row
  	string :gallery_name
  	integer :number_id
  	string :letter_id
  	boolean :fixed
  	string :opens
  	integer :condition
  	integer :rating
  	string :image
  	integer :status
  end
end

app/models/user.rb
class User < ActiveResource::Base
  self.site = ENV['api_url']
  add_response_method :http_response

  has_many :shops

  def self.roles
  	{ Cliente: :client, Vendedor: :seller }
  end
  def self.genders
  	{ Masculino: :male, Femenino: :female }
  end
  def self.id_types
  	[ :DNI, :CI, :Otro ]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	layout :set_layout
	
	def home
	end

	def packs
		roles = { visitante: :client, comerciante: :seller }
		@role = roles[params[:role].to_sym]
	end

	def blog
	end

	def article
	end

	def reset_password
		if params[:client_id]
			cookies[:reset_password] = {
				value: JSON.generate(params.permit(:client_id, :token, :uid)),
				expires: Time.now + 1.minute
			}
		elsif cookies[:reset_password].blank?
			redirect_to root_url
		end
	end

	def privacy_policy
	end

	def terms_and_conditions
	end

	private
		def set_layout
			if action_name.to_sym == :privacy_policy
				'privacy_policy'
			else
				'pages'
			end
		end
end

app/controllers/panel_controller.rb
class PanelController < ApplicationController
	layout :select_layout

  def home
  	@users = User.all
  	@categories = Category.all
  	@shops = Shop.all
  	@contacts = Contact.all
  end

  def login
  end

  private
  	def select_layout
  		'clean' if action_name.to_sym == :login
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/head_helper.rb
module HeadHelper
	def head_allow_robots?
		true
	end

	def head_title
		request.subdomain.starts_with?('panel') ? 'Panel SaladaApp' : 'SaladaApp'
	end

	def head_description
		''
	end

	def head_og_image
		asset_url 'logo.jpg'
	end

	def head_og_image_width
		'102'
	end

	def head_og_image_height
		'130'
	end
end

app/helpers/pages_helper.rb
module PagesHelper
	def pages_packs
		{
			client: [
				{
					class: 'pack',
					title: 'Visitante Free',
					subtitle: 'GRATIS',
					details: {
						'Crear y editar perfil.': 'Si',
						'Ver todos los galpones.': 'Si',
						'Ver todos los rubros de productos.': 'Si',
						'Ver todos los puestos.': 'Si',
						'Busqueda por productos.': 'Si',
						'Busqueda por palabras.': 'Si',
						'Enviar y recibir mensajes.': 'Si',
						'Ver destacado del día.': 'Si',
						'Acceder a otros destacados.': 'Si',
						'Generar reservas de productos.': 'No',
						'Promos/Ofertas de productos.': 'No'
					}
				},
				{
					class: 'pack pack-primary',
					title: 'Visitante Premium',
					subtitle: '$49,99<small>/Mes</small>',
					details: {
						'Crear y editar perfil.': 'Si',
						'Ver todos los galpones.': 'Si',
						'Ver todos los rubros de productos.': 'Si',
						'Ver todos los puestos.': 'Si',
						'Busqueda por productos.': 'Si',
						'Busqueda por palabras.': 'Si',
						'Enviar y recibir mensajes.': 'Si',
						'Ver destacado del día.': 'Si',
						'Acceder a otros destacados.': 'Si',
						'Generar reservas de productos.': 'Si',
						'Promos/Ofertas de productos.': 'Si'
					}
				}
			],
			seller: [
				{
					class: 'pack',
					title: 'Comerciante Free',
					subtitle: 'GRATIS',
					promotion: '&nbsp;',
					details: {
						'Crear y editar perfil.': 'Si',
						'Crear y editar datos de ubicación del puesto.': 'Si',
						'Crear y editar datos de rubro del puesto.': 'Si',
						'Publicar productos.': 'Solo 5',
						'Publicar avisos destacados.': 'No',
						'Imágenes por producto.': '1',
						'Precio por producto.': '1',
						'Publicar ofertas por producto.': 'No',
						'Ver rankings de reservas.': 'No',
						'Informe de analytics.': 'No',
						'Acciones de marketing sobre la base de visitantes.': 'No',
						'Validar tu puesto en el mapa.': 'No'
					}
				},
				{
					class: 'pack pack-primary',
					title: 'Comerciante Premium',
					subtitle: '$199,99<small>/Mes</small>*',
					promotion: '<sup>*</sup>Pago anual adelantado en efectivo $1.999,99',
					details: {
						'Crear y editar perfil.': 'Si',
						'Crear y editar datos de ubicación del puesto.': 'Si',
						'Crear y editar datos de rubro del puesto.': 'Si',
						'Publicar productos.': 'Ilimitado',
						'Publicar avisos destacados.': 'Si',
						'Imágenes por producto.': '5',
						'Precio por producto.': '1',
						'Publicar ofertas por producto.': 'Si',
						'Ver rankings de reservas.': 'Si',
						'Informe de analytics.': 'Si',
						'Acciones de marketing sobre la base de visitantes.': 'Si',
						'Validar tu puesto en el mapa.': 'Si'
					}
				}
			]
		}
	end
end

app/helpers/panel_helper.rb
module PanelHelper
	def sidebar_link_class(controller, action = false)
		'active' if controller_name.to_sym == controller && (action.blank? || action_name.to_sym == action)
	end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer_pages.html.erb
<footer>
	<div class="container">
		<div class="brand">
			<%= link_to root_path do %>
				<%= image_tag 'saladaapp_pages_logo.png' %>
			<% end %>
		</div>
		<nav class="app-nav">
			<div class="vertical-align h-xs-40">
				<div class="middle">
					<%= render 'layouts/nav_pages_list' %>
				</div>
			</div>
		</nav>
		<div class="footer-legend">
			<p>
				<span>2017 - Salada App. Todos los derechos reservados.</span>
				Powered by
				<%= link_to 'http://vertigodesign.com.ar', target: '_blank' do %>
					<%= image_tag 'logo-vertigo.png' %>
				<% end %>
			</p>
		</div>
	</div>
</footer>

app/views/layouts/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
<title><%= head_title %></title>
<meta name="description" content="<%= head_description %>">
<% if head_allow_robots? %>
  <META NAME="robots" CONTENT="ALL">
  <meta name="robots" content="index,follow"/>
  <meta name="googlebot" content="index,follow"/>
<% end %>
<link rel="canonical" href="<%= request.original_url %>">
<!--OPEN GRAPH-->
<meta property="og:locale:locale" content="es_ES">
<meta property="og:title" content="<%= head_title %>">
<meta property="og:site_name" content="SaladaApp">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= request.original_url %>">
<meta property="og:description" content="<%= head_description %>">
<meta property="og:image" content="<%= head_og_image %>">
<meta property="og:image:type" content="image/jpeg">
<meta property="og:image:width" content="<%= head_og_image_width %>">
<meta property="og:image:height" content="<%= head_og_image_height %>">
<!--END OPEN GRAPH-->
<link rel="apple-touch-icon" sizes="57x57" href="<%= asset_path 'apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= asset_path 'apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= asset_path 'apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= asset_path 'apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= asset_path 'apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= asset_path 'apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= asset_path 'apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= asset_path 'apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= asset_path 'apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="192x192"  href="<%= asset_path 'android-icon-192x192.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= asset_path 'favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= asset_path 'favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= asset_path 'favicon-16x16.png' %>">
<link href='https://fonts.googleapis.com/css?family=Roboto+Condensed:400,300italic,300,400italic,700,700italic' rel='stylesheet' type='text/css'>

app/views/layouts/_mp_sdk.html.erb
<script type="text/javascript">
(function(){function $MPC_load(){window.$MPC_loaded !== true && (function(){var s = document.createElement("script");s.type = "text/javascript";s.async = true;s.src = document.location.protocol+"//secure.mlstatic.com/mptools/render.js";var x = document.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);window.$MPC_loaded = true;})();}window.$MPC_loaded !== true ? (window.attachEvent ?window.attachEvent('onload', $MPC_load) : window.addEventListener('load', $MPC_load, false)) : null;})();
</script>

app/views/layouts/_nav_pages_list.html.erb
<ul class="<%= list_class rescue 'list-inline' %>">
	<li><%= link_to 'PACKS', root_path + '#packs', class: 'scroll-hash' %></li>
	<li><%= link_to 'DESCARGAR', root_path + '#download', class: 'scroll-hash' %></li>
	<li><%= link_to 'BLOG', blog_path %></li>
	<li><%= link_to 'TÉRMINOS Y CONDICIONES', terms_and_conditions_path %></li>
	<li><%= link_to 'CONTACTO', root_path + '#contact', class: 'scroll-hash' %></li>
	<li class="social-media">
		<%= link_to 'https://www.facebook.com/SaladaApp-2213308965591500/', target: '_blank' do %>
			<i class="fa fa-facebook-square"></i>
		<% end %>
		<%= link_to 'https://www.instagram.com/saladaapp/', target: '_blank' do %>
			<i class="fa fa-instagram"></i>
		<% end %>
		<%= link_to 'https://api.whatsapp.com/send?phone=5491134482777', target: '_blank' do %>
			<i class="fa fa-whatsapp"></i>
		<% end %>
	</li>
	<!--
		<li class="auth-hide"><%= link_to 'REGISTRATE', '#' %></li>
		<li class="auth-hide"><%= link_to 'INICIAR SESIÓN', '#', data: { toggle: 'modal', target: '#modalLogin' } %></li>
		<li class="auth-show"><%= link_to 'CERRAR SESIÓN', '#', data: { auth: 'signOut' } %></li>
	-->
</ul>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" style="margin-bottom:0">
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="<%= panel_path %>">
			<img alt="Brand" src="<%= asset_path 'favicon-96x96.png' %>" width="20px" height="20px">
			<span class="navbar-brand-text">SaladaApp</span>
		</a>
	</div>
	<ul class="nav navbar-top-links navbar-right">
		<% if false %>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-envelope fa-fw"></i> <i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-messages">
					<li>
						<a href="#">
							<div>
								<strong>John Smith</strong>
								<span class="pull-right text-muted">
									<em>Yesterday</em>
								</span>
							</div>
							<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">
							<div>
								<strong>John Smith</strong>
								<span class="pull-right text-muted">
									<em>Yesterday</em>
								</span>
							</div>
							<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">
							<div>
								<strong>John Smith</strong>
								<span class="pull-right text-muted">
									<em>Yesterday</em>
								</span>
							</div>
							<div>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque eleifend...</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a class="text-center" href="#">
							<strong>Read All Messages</strong>
							<i class="fa fa-angle-right"></i>
						</a>
					</li>
				</ul>
				<!-- /.dropdown-messages -->
			</li>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-tasks fa-fw"></i> <i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-tasks">
					<li>
						<a href="#">
							<div>
								<p>
									<strong>Task 1</strong>
									<span class="pull-right text-muted">40% Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
										<span class="sr-only">40% Complete (success)</span>
									</div>
								</div>
							</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">
							<div>
								<p>
									<strong>Task 2</strong>
									<span class="pull-right text-muted">20% Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100" style="width: 20%">
										<span class="sr-only">20% Complete</span>
									</div>
								</div>
							</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">
							<div>
								<p>
									<strong>Task 3</strong>
									<span class="pull-right text-muted">60% Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-warning" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%">
										<span class="sr-only">60% Complete (warning)</span>
									</div>
								</div>
							</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a href="#">
							<div>
								<p>
									<strong>Task 4</strong>
									<span class="pull-right text-muted">80% Complete</span>
								</p>
								<div class="progress progress-striped active">
									<div class="progress-bar progress-bar-danger" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
										<span class="sr-only">80% Complete (danger)</span>
									</div>
								</div>
							</div>
						</a>
					</li>
					<li class="divider"></li>
					<li>
						<a class="text-center" href="#">
							<strong>See All Tasks</strong>
							<i class="fa fa-angle-right"></i>
						</a>
					</li>
				</ul>
			</li>
		<% end %>
		<% if @panel_data[:unread_contacts_count] > 0 %>
			<li class="dropdown">
				<a class="dropdown-toggle" data-toggle="dropdown" href="#">
					<i class="fa fa-bell fa-fw"></i> <i class="fa fa-caret-down"></i>
				</a>
				<ul class="dropdown-menu dropdown-alerts">
					<li>
						<a href="<%= contacts_path %>">
							<div>
								<i class="fa fa-support fa-fw"></i> Contactos
								<span class="pull-right text-muted small"><%= @panel_data[:unread_contacts_count] %> sin leer</span>
							</div>
						</a>
					</li>
					<!--li class="divider"></li>
					<li>
						<a class="text-center" href="javascript:void(0);">
							<strong>Ver todas las alertas</strong>
							<i class="fa fa-angle-right"></i>
						</a>
					</li-->
				</ul>
			</li>
		<% end %>
		<li class="dropdown auth-show">
			<a class="dropdown-toggle" data-toggle="dropdown" href="#">
				<i class="fa fa-user fa-fw"></i> <i class="fa fa-caret-down"></i>
			</a>
			<ul class="dropdown-menu dropdown-user">
				<li><a><i class="fa fa-user fa-fw"></i> <span data-auth-bind="name"></span></a></li>
				<!--li><a href="#"><i class="fa fa-gear fa-fw"></i> Settings</a></li-->
				<li class="divider"></li>
				<li><a href="#" data-auth="signOut"><i class="fa fa-sign-out fa-fw"></i> Logout</a></li>
			</ul>
		</li>
		<li class="auth-hide">
			<a href="<%= panel_login_path %>">
				<i class="fa fa-sign-in fa-fw" aria-hidden="true"></i>
			</a>
		</li>
	</ul>
	<div class="navbar-default sidebar" role="navigation">
		<div class="sidebar-nav navbar-collapse" aria-expanded="false" style="height: 1px;">
			<ul class="nav in" id="side-menu">
				<li class="sidebar-search">
          <div class="input-group custom-search-form">
          	<input type="text" class="form-control" placeholder="Search...">
          	<span class="input-group-btn">
          		<button class="btn btn-default" type="button">
          			<i class="fa fa-search"></i>
          		</button>
          	</span>
          </div>
        </li>
				<li>
					<a href="<%= panel_path %>" class="<%= sidebar_link_class(:panel, :home) %>"><i class="fa fa-dashboard fa-fw"></i> Panel</a>
				</li>
				<li class="<%= sidebar_link_class(:users) %>">
					<a href="#"><i class="fa fa-users fa-fw"></i> Usuarios<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse <%= 'in' if controller_name.to_sym == :users %>">
						<li>
							<a href="<%= users_path %>" class="<%= sidebar_link_class(:users, :index) %>">Lista de usuarios</a>
						</li>
					</ul>
				</li>
				<li class="<%= sidebar_link_class(:categories) %>">
					<a href="#"><i class="fa fa-tasks fa-fw"></i> Categorías<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse <%= 'in' if controller_name.to_sym == :categories %>">
						<li>
							<%= link_to 'Agregar Categoría', new_category_path, class: sidebar_link_class(:categories, :new) %>
						</li>
						<li>
							<a href="<%= categories_path %>" class="<%= sidebar_link_class(:categories, :index) %>">Lista de categorías</a>
						</li>
					</ul>
				</li>
				<li class="<%= sidebar_link_class(:shops) %>">
					<a href="#"><i class="fa fa-shopping-cart fa-fw"></i> Puestos<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse <%= 'in' if controller_name.to_sym == :shops %>">
						<li>
							<%= link_to 'Agregar Puesto', new_shop_path, class: sidebar_link_class(:shops, :new) %>
						</li>
						<li>
							<a href="<%= shops_path %>" class="<%= sidebar_link_class(:shops, :index) %>">Lista de puestos</a>
						</li>
					</ul>
				</li>
				<li class="<%= sidebar_link_class(:contacts) %>">
					<a href="#"><i class="fa fa-support fa-fw"></i> Contactos<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse <%= 'in' if controller_name.to_sym == :contacts %>">
						<li>
							<%= link_to 'Agregar Contacto', new_contact_path, class: sidebar_link_class(:contacts, :new) %>
						</li>
						<li>
							<a href="<%= contacts_path %>" class="<%= sidebar_link_class(:contacts, :index) %>">Lista de contactos</a>
						</li>
					</ul>
				</li>
				<!--li>
					<a href="forms.html"><i class="fa fa-edit fa-fw"></i> Forms</a>
				</li>
				<li>
					<a href="#"><i class="fa fa-wrench fa-fw"></i> UI Elements<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse">
						<li>
							<a href="panels-wells.html">Panels and Wells</a>
						</li>
						<li>
							<a href="buttons.html">Buttons</a>
						</li>
						<li>
							<a href="notifications.html">Notifications</a>
						</li>
						<li>
							<a href="typography.html">Typography</a>
						</li>
						<li>
							<a href="icons.html"> Icons</a>
						</li>
						<li>
							<a href="grid.html">Grid</a>
						</li>
					</ul>
				</li>
				<li>
					<a href="#"><i class="fa fa-sitemap fa-fw"></i> Multi-Level Dropdown<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse">
						<li>
							<a href="#">Second Level Item</a>
						</li>
						<li>
							<a href="#">Second Level Item</a>
						</li>
						<li>
							<a href="#">Third Level <span class="fa arrow"></span></a>
							<ul class="nav nav-third-level collapse">
								<li>
									<a href="#">Third Level Item</a>
								</li>
								<li>
									<a href="#">Third Level Item</a>
								</li>
								<li>
									<a href="#">Third Level Item</a>
								</li>
								<li>
									<a href="#">Third Level Item</a>
								</li>
							</ul>
						</li>
					</ul>
				</li>
				<li>
					<a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
					<ul class="nav nav-second-level collapse">
						<li>
							<a href="blank.html">Blank Page</a>
						</li>
						<li>
							<a href="login.html">Login Page</a>
						</li>
					</ul>
				</li-->
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/_navigation_pages.html.erb
<header>
	<div class="container">
		<div class="brand">
			<%= link_to root_path do %>
				<%= image_tag 'saladaapp_pages_logo.png' %>
			<% end %>
		</div>
		<nav class="app-nav">
			<div class="vertical-align h-xs-40">
				<div class="middle">
					<%= render 'layouts/nav_pages_list' %>
				</div>
			</div>
		</nav>
		<%= link_to '#', class: 'mobile-nav-trigger' do %>
			<i class="fa fa-bars" aria-hidden="true"></i>
		<% end %>
	</div>
</header>

app/views/layouts/_navigation_pages_mobile.html.erb
<div class="mobile-nav">
	<nav class="app-nav-mobile">
		<%= render 'layouts/nav_pages_list', list_class: 'list-unstyled' %>
	</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head prefix="og: http://ogp.me/ns#">
	<%= render 'layouts/head' %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper" class="in">
		<%= render 'layouts/navigation' %>
		<div id="page-wrapper">
			<%= yield %>
		</div>
	</div>
	<%# render 'layouts/footer' %>
	<script>
		$(function() {
			<% if notice.present? %>
				Utils.notification('notice', '<%= notice.html_safe %>');
			<% end %>
			<% if alert.present? %>
				Utils.notification('alert', '<%= alert.html_safe %>');
			<% end %>
			<%= content_for :extra_js %>
		});
	</script>
</body>
</html>

app/views/layouts/privacy_policy.html.erb
<!DOCTYPE html>
<html lang="<%= I18n.locale %>">
<head prefix="og: http://ogp.me/ns#">
	<%= render 'layouts/head' %>
	<%= stylesheet_link_tag    'application_policy', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application_policy', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="view-pages">
	<%= yield %>
</body>
</html>

app/views/pages/blog.html.erb
<% content_for :extra_js do %>
	Blog.init('<%= ENV['api_url'] %>');
<% end %>

<section class="relative bgi-blog cover c-white pt-xs-90 pb-xs-60 ptb-sm-130">
	<div class="container">
		<div class="row">
			<div class="col-xs-7 col-xs-offset-5 col-sm-4 col-sm-offset-6">
				<h1>BLOG</h1>
				<p>Llegó <b>Salada</b>App, la manera de recorrer la feria más grande de Latinoamérica desde tu dispositivo SmartPhone y Tablet.</p>
			</div>
		</div>
	</div>
</section>
<section class="relative bg-light-grey">
	<div class="container">
		<div id="articles"></div>
		<%= link_to '#', class: 'round-btn article-plus', id: 'getPage' do %>
			<span>+</span>
			<span><i class="fa fa-spinner fa-pulse"></i></span>
		<% end %>
	</div>
</section>

<article id="articleTemplate" class="article" style="display:none;">
	<%= link_to article_path('-') do %>
		<div class="article-image">
			<%= image_tag '' %>
		</div>
		<div class="article-container">
			<div class="article-slap">
				<span></span>
				<span></span>
			</div>
			<div class="article-body">
				<h3 class="article-title"></h3>
				<p class="article-text"></p>
				<span class="btn btn-primary">Ver más</span>
			</div>
		</div>
	<% end %>
</article>